// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { env } from "./src/config/env";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node -r tsconfig-paths/register prisma/seed.ts",
  },
  datasource: {
    url: env.DIRECT_URL,
  },
});
